org.slf4j.simpleLogger.logFile=System.out
org.slf4j.simpleLogger.defaultLogLevel=info
org.slf4j.simpleLogger.showShortLogName=true
org.slf4j.simpleLogger.log.org.apache.kafka=debug
logging.level.ru.yandex.practicum.telemetry=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.validation=DEBUG
logging.level.com.fasterxml.jackson.databind=DEBUG
#topics
kafka.topics.sensors=telemetry.sensors.v1
kafka.topics.hubs=telemetry.hubs.v1
#kafka-server
spring.kafka.bootstrap-servers=localhost:9092